### ISSUE TITLE
couldn't use the library.

### ISSUE THREAD

**Issue by rahmanshaber** [marcusbritanicus/PdfWidget#1]
sorry for silly problem.
i am trying to make a example with the pdf wideget.
but tried this.
![sd](https://user-images.githubusercontent.com/30831735/36851022-74ec9740-1d92-11e8-8975-2ee5549d11b9.png)

please can you point me how to do this correctly

**Comment by marcusbritanicus** [comment]
I have added an example. Please check the example.

**Comment by rahmanshaber** [comment]
i tried the example.just unpacked it.and run example.pro .
then adde like this and got this.
![er](https://user-images.githubusercontent.com/30831735/36899441-57fa807c-1e49-11e8-8383-6bdb41b889b0.png)

please help me.i need this badly.like suggesting it on a project.(like udisk2)

**Comment by marcusbritanicus** [comment]
When you're running the example, you'll have to take care of two things:

1. You're running the example from the `example` folder. So you'll have to specify the library path: LD_LIBRARY_PATH="../lib/"
2. Line 37: `PdfDocument *Pdf = new PdfDocument( argv[ 1 ] );` The `argv[1]` means that you'll have to specify the Pdf file name in the command line.

So your command line should look like
`$ ./pdfwidget /path/to/a/valif/pdf/file.pdf`

**Comment by rahmanshaber** [comment]
thanks for the help.
done this .
![ml](https://user-images.githubusercontent.com/30831735/36930380-b39bf9a8-1ec9-11e8-81eb-0ed4355b7541.png)
you won't believe how good this app you made.
i tried to find pdf viewer app in GPL .but all are huge and complicated.

In your redme file you mistakenly write the app name "NEWBREEZE" instated of "Pdfwidget".

**Comment by marcusbritanicus** [comment]
Thank you. I too had great difficulty to get a simple pdfviewer app. I am using this code to preview PDFs in NewBreeze.
